=== vova120880/json_schemes/ccu.schema.json
{
  "$id": "https://raw.githubusercontent.com/vova120880/json_schemes/master/ccu.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "description": "коммутатор",
  "properties": {
    "SM_SIZE": {
      "type": "string",
      "description": "размерность коммутатора",
      "enum": [
        "256"
      ]
    },
    "MKU": {
      "$ref": "https://raw.githubusercontent.com/vova120880/json_schemes/master/cross.schema.json",
      "description": "кассета"
    },
    "MAIN": {
      "$ref": "https://raw.githubusercontent.com/vova120880/json_schemes/master/cross.schema.json",
      "description": "кассета"
    },
    "EXT": {
      "type": "array",
      "description": "кассеты расширения",
      "items": {
        "type": "object",
        "description": "описание одной кассеты расширения (платы, вставленной в позицию главной кассеты)",
        "properties": {
          "index": {
            "type": "integer",
            "description": "позиция в главной кассете"
          },
          "data": {
            "type": "array",
            "description": "описание кассет расширения (шасси) (ММЗ, ММОЗ-01 - 1 шасси, ММЗ-01 - 2 шасси, ММОЗ - 4 шасси)",
            "items": {
              "type": "object",
              "description": "шасси кассеты расширения",
              "properties": {
                "index": {
                  "type": "integer",
                  "description": "индекс"
                },
                "data": {
                  "$ref": "https://raw.githubusercontent.com/vova120880/json_schemes/master/cross.schema.json",
                  "description": "кассета"
                }
              },
              "required": [
                "index",
                "data"
              ],
              "additionalProperties": false
            }
          }
        },
        "required": [
          "index",
          "data"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": [
    "SM_SIZE",
    "MKU",
    "MAIN",
    "EXT"
  ],
  "additionalProperties": false
}

=== vova120880/json_schemes/ccu.example.json
{
  "SM_SIZE": "256",
  "MKU": {
    "CROSS": "17R",
    "BOARDS": []
  },
  "MAIN": {
    "CROSS": "17R",
    "BOARDS": [
      {
        "index": 2,
        "data": {
          "TYPE": "MMD",
          "TRUNKS": [
            {
              "index": 0,
              "data": {
                "TYPE": "NATIVE",
                "PORTS": [
                  "CTL",
                  "AK",
                  "AK",
                  "AK",
                  "AK",
                  "AK",
                  "AK",
                  "AK",
                  "AK",
                  "AK",
                  "AK",
                  "AK",
                  "AK",
                  "AK",
                  "AK",
                  "AK"
                ]
              }
            }
          ]
        }
      }
    ]
  },
  "EXT": []
}
